services:
  mysql:
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
